# Generated by Django 5.0.6 on 2026-07-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
