# Generated by Django 5.0.6 on 2026-07-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_accommodation_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='direction',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure')], default='arrival', max_length=10),
        ),
    ]
