# Generated by Django 5.0.6 on 2026-07-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('vehicle', models.CharField(blank=True, max_length=100)),
                ('confirmation_code', models.CharField(blank=True, max_length=40)),
                ('pickup_location', models.CharField(blank=True, max_length=300)),
                ('dropoff_location', models.CharField(blank=True, max_length=300)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('dropoff_time', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='trips.trip')),
            ],
            options={
                'ordering': ['pickup_time', 'id'],
            },
        ),
    ]
