# Generated by Django 5.0.6 on 2026-07-13 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_groceryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('shopping', 'Shopping'), ('activity', 'Activity'), ('sightseeing', 'Sightseeing'), ('outdoors', 'Outdoors'), ('nightlife', 'Nightlife'), ('other', 'Other')], default='other', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested', models.ManyToManyField(blank=True, related_name='interested_pois', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='trips.trip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
